
cd E:
mkdir Home-500-MB-Qutoamk
mkdir RoamingProfile-500-MB-Qutoa
mkdir Firma1
cd Firma1
mkdir Administrator-opgaver
mkdir Ledelse
mkdir Bestyrelsmøde
mkdir Repsedler
mkdir Elever
mkdir Personaleforening
mkdir VærksFørere
mkdir SalgIndkøb
mkdir Manualer
mkdir Progammer
mkdir Personal-Sager
mkdir Afdelinger
cd Afdelinger
mkdir Afdelinger
mkdir Indkøb
mkdir IT
mkdir Salg
mkdir Diretion
mkdir Personale
mkdir Økonomi
mkdir Produktions-afdeling
cd Produktions-afdeling
mkdir Lager
mkdir Produktions
mkdir Reparation